import argparse
import math
import sys
from pathlib import Path

import pychrono.core as chrono

sys.path.append(str(Path(__file__).resolve().parent))
from visual_helpers import attach_spring_visual, update_system_visuals


# Reproduces EXUDYN TestModels/MiniExamples/ObjectGenericODE2.py.
# The source builds a two-node GenericODE2 system with M=0.5 I, coupled
# stiffness/damping matrices generated by two equal spring-damper spans, and a
# constant 10 N x-load on the second node.  The PyChrono scene uses the same
# physical two-mass/two-spring analogue and renders both connectors as coils.

MASS = 0.5
STIFFNESS = 5000.0
DAMPING = 50.0
LOAD = 10.0
REST_0 = 1.0
REST_1 = 1.0
GROUND_X = -1.0
MASS0_X = 0.0
MASS1_X = 1.0
END_TIME = 1.0
STEP = 5.0e-4
STATIC_U0 = LOAD / STIFFNESS
STATIC_U1 = 2.0 * LOAD / STIFFNESS
REFERENCE_SOURCE_POSITION_X = MASS1_X + STATIC_U1


def color(r, g, b):
    return chrono.ChColor(r, g, b)


def rhs(_time, state):
    u0, u1, v0, v1 = state
    spring0 = STIFFNESS * u0 + DAMPING * v0
    spring1 = STIFFNESS * (u1 - u0) + DAMPING * (v1 - v0)
    a0 = (-spring0 + spring1) / MASS
    a1 = (LOAD - spring1) / MASS
    return (v0, v1, a0, a1)


def rk4_step(time, state, step):
    def add_scaled(base, slope, scale):
        return tuple(base[i] + scale * slope[i] for i in range(4))

    k1 = rhs(time, state)
    k2 = rhs(time + 0.5 * step, add_scaled(state, k1, 0.5 * step))
    k3 = rhs(time + 0.5 * step, add_scaled(state, k2, 0.5 * step))
    k4 = rhs(time + step, add_scaled(state, k3, step))
    return tuple(state[i] + step * (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]) / 6.0 for i in range(4))


def solve(duration=END_TIME, step=STEP):
    time = 0.0
    state = (0.0, 0.0, 0.0, 0.0)
    while time < duration - 1e-12:
        dt = min(step, duration - time)
        state = rk4_step(time, state, dt)
        time += dt
    return state


class MutableSegment:
    def __init__(self, system, name, tint, thickness=4):
        self.body = chrono.ChBody()
        self.body.SetName(name)
        self.body.SetFixed(True)
        self.body.EnableCollision(False)
        self.shape = chrono.ChVisualShapeSegment()
        self.shape.SetMutable(True)
        self.shape.SetColor(tint)
        self.shape.SetThickness(thickness)
        self.body.AddVisualShape(self.shape)
        system.AddBody(self.body)

    def update(self, point_a, point_b):
        self.shape.SetLineGeometry(chrono.ChLineSegment(point_a, point_b))
        self.body.UpdateVisualModel()


class LoadArrow:
    def __init__(self, system):
        self.main = MutableSegment(system, "ObjectGenericODE2 constant load arrow", color(0.92, 0.55, 0.05), 5)
        self.tip_a = MutableSegment(system, "ObjectGenericODE2 load arrow tip a", color(0.92, 0.55, 0.05), 4)
        self.tip_b = MutableSegment(system, "ObjectGenericODE2 load arrow tip b", color(0.92, 0.55, 0.05), 4)

    def update(self, mass_pos):
        start = mass_pos + chrono.ChVector3d(0.0, 0.16, 0.0)
        end = start + chrono.ChVector3d(0.30, 0.0, 0.0)
        self.main.update(start, end)
        self.tip_a.update(end, end + chrono.ChVector3d(-0.060, 0.032, 0.0))
        self.tip_b.update(end, end + chrono.ChVector3d(-0.060, -0.032, 0.0))


def make_body(system, name, x, radius, tint, fixed=False):
    body = chrono.ChBodyEasySphere(radius, 1000, True, False)
    body.SetName(name)
    body.SetFixed(fixed)
    body.EnableCollision(False)
    body.SetMass(MASS)
    body.SetInertiaXX(chrono.ChVector3d(0.01, 0.01, 0.01))
    body.SetPos(chrono.ChVector3d(x, 0.0, 0.0))
    body.GetVisualShape(0).SetColor(tint)
    system.AddBody(body)
    return body


def add_coil_spring(system, name, body_a, body_b, rest_length):
    spring = chrono.ChLinkTSDA()
    spring.SetName(name)
    spring.Initialize(body_b, body_a, True, chrono.ChVector3d(0.0, 0.0, 0.0), chrono.ChVector3d(0.0, 0.0, 0.0))
    spring.SetRestLength(rest_length)
    spring.SetSpringCoefficient(STIFFNESS)
    spring.SetDampingCoefficient(DAMPING)
    system.AddLink(spring)
    spring_shape = chrono.ChVisualShapeSpring(0.045, 100, 13)
    spring_shape.SetColor(color(0.86, 0.16, 0.10))
    spring.AddVisualShape(spring_shape)
    attach_spring_visual(system, spring, 0.045, 100, 13, color(0.86, 0.16, 0.10))
    return spring


def make_ground_visuals(system, ground):
    rail = chrono.ChVisualShapeBox(2.75, 0.018, 0.018)
    rail.SetColor(color(0.42, 0.42, 0.42))
    ground.AddVisualShape(rail, chrono.ChFramed(chrono.ChVector3d(0.15, -0.16, 0.0)))

    wall = chrono.ChVisualShapeBox(0.06, 0.40, 0.18)
    wall.SetColor(color(0.55, 0.56, 0.55))
    ground.AddVisualShape(wall, chrono.ChFramed(chrono.ChVector3d(GROUND_X, 0.0, 0.0)))

    static_marker = chrono.ChVisualShapeBox(0.016, 0.22, 0.018)
    static_marker.SetColor(color(0.08, 0.08, 0.08))
    ground.AddVisualShape(static_marker, chrono.ChFramed(chrono.ChVector3d(REFERENCE_SOURCE_POSITION_X, -0.16, 0.0)))


def build_system():
    system = chrono.ChSystemNSC()
    system.SetGravitationalAcceleration(chrono.ChVector3d(0.0, 0.0, 0.0))

    ground = chrono.ChBody()
    ground.SetName("ObjectGenericODE2 ground")
    ground.SetFixed(True)
    ground.EnableCollision(False)
    ground.SetPos(chrono.ChVector3d(0.0, 0.0, 0.0))
    make_ground_visuals(system, ground)
    system.AddBody(ground)

    mass0 = make_body(system, "ObjectGenericODE2 node 0 mass", MASS0_X, 0.070, color(0.12, 0.38, 0.88))
    mass1 = make_body(system, "ObjectGenericODE2 node 1 loaded mass", MASS1_X, 0.075, color(0.12, 0.58, 0.28))
    anchor = make_body(system, "ObjectGenericODE2 wall anchor", GROUND_X, 0.035, color(0.08, 0.08, 0.08), fixed=True)

    spring0 = add_coil_spring(system, "ObjectGenericODE2 ground-node0 spring-damper", anchor, mass0, REST_0)
    spring1 = add_coil_spring(system, "ObjectGenericODE2 node0-node1 spring-damper", mass0, mass1, REST_1)

    force = chrono.ChForce()
    force.SetF_x(chrono.ChFunctionConst(LOAD))
    mass1.AddForce(force)

    arrow = LoadArrow(system)
    items = {"ground": ground, "anchor": anchor, "mass0": mass0, "mass1": mass1, "spring0": spring0, "spring1": spring1, "arrow": arrow}
    system._object_generic_ode2_items = items
    update_visuals(system)
    return system, items


def update_visuals(system):
    items = system._object_generic_ode2_items
    items["arrow"].update(items["mass1"].GetPos())
    update_system_visuals(system)


def simulate(duration, step):
    system, items = build_system()
    while system.GetChTime() < duration - 1e-12:
        update_visuals(system)
        system.DoStepDynamics(min(step, duration - system.GetChTime()))
    update_visuals(system)
    return system, items


def run_visual(duration, step):
    import pychrono.irrlicht as chronoirr

    system, _items = build_system()
    vis = chronoirr.ChVisualSystemIrrlicht()
    vis.AttachSystem(system)
    vis.SetWindowSize(1024, 720)
    vis.SetWindowTitle("EXUDYN port: ObjectGenericODE2.py")
    vis.Initialize()
    vis.AddSkyBox()
    vis.AddCamera(chrono.ChVector3d(0.10, -3.1, 1.20), chrono.ChVector3d(0.08, 0.0, 0.0))
    vis.AddTypicalLights()

    while vis.Run() and system.GetChTime() < duration:
        update_visuals(system)
        vis.BeginScene()
        vis.Render()
        vis.EndScene()
        system.DoStepDynamics(step)


def print_result(duration, step):
    state = solve(duration, step)
    u0, u1, v0, v1 = state
    source_position = MASS1_X + u1
    static_error = math.sqrt((u0 - STATIC_U0) ** 2 + (u1 - STATIC_U1) ** 2)
    print(
        f"generic_ode2: t={duration:7.3f}  "
        f"u=({u0:+.12f},{u1:+.12f})  v=({v0:+.12e},{v1:+.12e})  "
        f"source_position_x={source_position:+.12f}  "
        f"static_error={static_error:.3e}"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--duration", type=float, default=END_TIME)
    parser.add_argument("--step", type=float, default=STEP)
    parser.add_argument("--no-vis", action="store_true")
    args = parser.parse_args()

    print("EXUDYN port: ObjectGenericODE2.py -> PyChrono GenericODE2 two-mass spring system")
    if args.no_vis:
        print_result(args.duration, args.step)
    else:
        run_visual(args.duration, args.step)


if __name__ == "__main__":
    main()
